In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt

In [2]:
## Path settings
results_dir = '/home/inffzy/Desktop/cogs189/cogs189_final_project/results'

LDA_2_path = os.path.join(results_dir, '2_LDA.npy')
LDA_CSP_2_path = os.path.join(results_dir, '2_LDA_CSP.npy')
LDA_SACSP_2_path = os.path.join(results_dir, '2_LDA_SACSP.npy')
LDA_4_path = os.path.join(results_dir, '4_LDA.npy')
LDA_CSP_4_path = os.path.join(results_dir, '4_LDA_CSP.npy')
LDA_SACSP_4_path = os.path.join(results_dir, '4_LDA_SACSP.npy')

training_report2_path = os.path.join(results_dir, 'training_report2.csv')
validation_report2_path = os.path.join(results_dir, 'validation_report2.csv')
testing_report2_path = os.path.join(results_dir, 'testing_report2.csv')

training_report4_path = os.path.join(results_dir, 'training_report4.csv')
validation_report4_path = os.path.join(results_dir, 'validation_report4.csv')
testing_report4_path = os.path.join(results_dir, 'testing_report4.csv')

In [3]:
## Load results
LDA_2 = np.load(LDA_2_path)
LDA_CSP_2 = np.load(LDA_CSP_2_path)
LDA_SACSP_2 = np.load(LDA_SACSP_2_path)
LDA_4 = np.load(LDA_4_path)
LDA_CSP_4 = np.load(LDA_CSP_4_path)
LDA_SACSP_4 = np.load(LDA_SACSP_4_path)

In [4]:
def get_acc_and_var(results, save_path=None):
    results_acc_over_experiment = np.mean(results, axis=0).round(2)
    results_std_over_experiment = np.std(results, axis=0).round(3)
    
    results_acc_over_subject = np.mean(results_acc_over_experiment, axis=0).round(2)
    results_std_over_subject = np.mean(results_std_over_experiment, axis=0).round(3)
    
    print(results_acc_over_experiment)
    print(results_acc_over_subject)
    print()
    print(results_std_over_experiment)
    print(results_std_over_subject)
    
    results_acc = np.concatenate((results_acc_over_experiment, np.atleast_2d(results_acc_over_subject)), axis=0)
    results_std = np.concatenate((results_std_over_experiment, np.atleast_2d(results_std_over_subject)), axis=0)
    
    return results_acc, results_std

In [5]:
LDA_2_acc, LDA_2_std = get_acc_and_var(LDA_2)
LDA_CSP_2_acc, LDA_CSP_2_std = get_acc_and_var(LDA_CSP_2)
LDA_SACSP_2_acc, LDA_SACSP_2_std = get_acc_and_var(LDA_SACSP_2)
LDA_4_acc, LDA_4_std = get_acc_and_var(LDA_4)
LDA_CSP_4_acc, LDA_CSP_4_std = get_acc_and_var(LDA_CSP_4)
LDA_SACSP_4_acc, LDA_SACSP_4_std = get_acc_and_var(LDA_SACSP_4)

[[0.89 0.52 0.58]
 [0.91 0.47 0.44]
 [0.91 0.54 0.45]
 [0.87 0.5  0.44]
 [0.83 0.44 0.42]
 [0.95 0.51 0.49]
 [0.8  0.46 0.46]
 [0.91 0.54 0.6 ]
 [0.95 0.48 0.49]
 [1.   0.45 0.48]
 [1.   0.64 0.58]
 [1.   0.54 0.48]]
[0.92 0.51 0.49]

[[0.039 0.052 0.054]
 [0.023 0.049 0.036]
 [0.04  0.041 0.06 ]
 [0.049 0.062 0.035]
 [0.024 0.08  0.07 ]
 [0.036 0.058 0.083]
 [0.041 0.047 0.057]
 [0.017 0.04  0.086]
 [0.025 0.044 0.08 ]
 [0.006 0.064 0.076]
 [0.    0.059 0.084]
 [0.    0.14  0.046]]
[0.025 0.061 0.064]
[[0.8  0.78 0.74]
 [0.71 0.67 0.52]
 [0.94 0.93 0.89]
 [0.79 0.78 0.62]
 [0.67 0.63 0.55]
 [0.79 0.77 0.51]
 [0.82 0.8  0.68]
 [0.96 0.96 0.91]
 [0.84 0.82 0.74]
 [0.95 0.94 0.9 ]
 [0.99 0.98 0.49]
 [0.98 0.98 0.84]]
[0.85 0.84 0.7 ]

[[0.019 0.02  0.047]
 [0.032 0.04  0.052]
 [0.016 0.015 0.032]
 [0.023 0.032 0.05 ]
 [0.04  0.032 0.066]
 [0.043 0.047 0.094]
 [0.033 0.035 0.063]
 [0.02  0.023 0.037]
 [0.026 0.032 0.07 ]
 [0.028 0.027 0.051]
 [0.015 0.021 0.115]
 [0.034 0.034 0.136]]
[0.0

In [6]:
training_report2 = np.zeros((13, 6))
validation_report2 = np.zeros((13, 6))
testing_report2 = np.zeros((13, 6))

training_report4 = np.zeros((13, 6))
validation_report4 = np.zeros((13, 6))
testing_report4 = np.zeros((13, 6))

In [7]:
training_report2[:, 0] = LDA_2_acc[:, 0]
training_report2[:, 1] = LDA_2_std[:, 0]
training_report2[:, 2] = LDA_CSP_2_acc[:, 0]
training_report2[:, 3] = LDA_CSP_2_std[:, 0]
training_report2[:, 4] = LDA_SACSP_2_acc[:, 0]
training_report2[:, 5] = LDA_SACSP_2_std[:, 0]
print(training_report2)
np.savetxt(training_report2_path, training_report2, fmt='%1.3f')

[[0.89  0.039 0.8   0.019 0.77  0.052]
 [0.91  0.023 0.71  0.032 0.64  0.036]
 [0.91  0.04  0.94  0.016 0.89  0.037]
 [0.87  0.049 0.79  0.023 0.68  0.053]
 [0.83  0.024 0.67  0.04  0.66  0.035]
 [0.95  0.036 0.79  0.043 0.68  0.034]
 [0.8   0.041 0.82  0.033 0.6   0.052]
 [0.91  0.017 0.96  0.02  0.93  0.014]
 [0.95  0.025 0.84  0.026 0.75  0.044]
 [1.    0.006 0.95  0.028 0.95  0.03 ]
 [1.    0.    0.99  0.015 0.91  0.035]
 [1.    0.    0.98  0.034 0.92  0.082]
 [0.92  0.025 0.85  0.027 0.78  0.042]]


In [8]:
validation_report2[:, 0] = LDA_2_acc[:, 1]
validation_report2[:, 1] = LDA_2_std[:, 1]
validation_report2[:, 2] = LDA_CSP_2_acc[:, 1]
validation_report2[:, 3] = LDA_CSP_2_std[:, 1]
validation_report2[:, 4] = LDA_SACSP_2_acc[:, 1]
validation_report2[:, 5] = LDA_SACSP_2_std[:, 1]
print(validation_report2)
np.savetxt(validation_report2_path, validation_report2, fmt='%1.3f')

[[0.52  0.052 0.78  0.02  0.75  0.064]
 [0.47  0.049 0.67  0.04  0.6   0.039]
 [0.54  0.041 0.93  0.015 0.87  0.054]
 [0.5   0.062 0.78  0.032 0.63  0.071]
 [0.44  0.08  0.63  0.032 0.64  0.035]
 [0.51  0.058 0.77  0.047 0.63  0.043]
 [0.46  0.047 0.8   0.035 0.57  0.064]
 [0.54  0.04  0.96  0.023 0.92  0.017]
 [0.48  0.044 0.82  0.032 0.74  0.04 ]
 [0.45  0.064 0.94  0.027 0.92  0.035]
 [0.64  0.059 0.98  0.021 0.87  0.032]
 [0.54  0.14  0.98  0.034 0.88  0.11 ]
 [0.51  0.061 0.84  0.03  0.75  0.05 ]]


In [9]:
testing_report2[:, 0] = LDA_2_acc[:, 2]
testing_report2[:, 1] = LDA_2_std[:, 2]
testing_report2[:, 2] = LDA_CSP_2_acc[:, 2]
testing_report2[:, 3] = LDA_CSP_2_std[:, 2]
testing_report2[:, 4] = LDA_SACSP_2_acc[:, 2]
testing_report2[:, 5] = LDA_SACSP_2_std[:, 2]
print(testing_report2)
np.savetxt(testing_report2_path, testing_report2, fmt='%1.3f')

[[0.58  0.054 0.74  0.047 0.67  0.055]
 [0.44  0.036 0.52  0.052 0.44  0.059]
 [0.45  0.06  0.89  0.032 0.85  0.077]
 [0.44  0.035 0.62  0.05  0.53  0.064]
 [0.42  0.07  0.55  0.066 0.5   0.066]
 [0.49  0.083 0.51  0.094 0.49  0.066]
 [0.46  0.057 0.68  0.063 0.49  0.08 ]
 [0.6   0.086 0.91  0.037 0.88  0.051]
 [0.49  0.08  0.74  0.07  0.68  0.033]
 [0.48  0.076 0.9   0.051 0.92  0.04 ]
 [0.58  0.084 0.49  0.115 0.66  0.119]
 [0.48  0.046 0.84  0.136 0.54  0.136]
 [0.49  0.064 0.7   0.068 0.64  0.07 ]]


In [10]:
training_report4[:, 0] = LDA_4_acc[:, 0]
training_report4[:, 1] = LDA_4_std[:, 0]
training_report4[:, 2] = LDA_CSP_4_acc[:, 0]
training_report4[:, 3] = LDA_CSP_4_std[:, 0]
training_report4[:, 4] = LDA_SACSP_4_acc[:, 0]
training_report4[:, 5] = LDA_SACSP_4_std[:, 0]
print(training_report4)
np.savetxt(training_report4_path, training_report4, fmt='%1.3f')

[[0.81  0.025 0.75  0.029 0.66  0.026]
 [0.8   0.026 0.67  0.027 0.49  0.026]
 [0.76  0.021 0.79  0.022 0.76  0.038]
 [0.67  0.029 0.56  0.031 0.42  0.02 ]
 [0.71  0.033 0.46  0.022 0.42  0.016]
 [0.91  0.024 0.58  0.039 0.49  0.04 ]
 [0.68  0.044 0.82  0.019 0.48  0.026]
 [0.79  0.025 0.86  0.018 0.73  0.022]
 [0.86  0.025 0.75  0.019 0.6   0.05 ]
 [0.99  0.008 0.91  0.025 0.88  0.068]
 [1.    0.    0.96  0.018 0.85  0.039]
 [1.    0.    0.95  0.033 0.76  0.063]
 [0.83  0.022 0.75  0.025 0.63  0.036]]


In [11]:
validation_report4[:, 0] = LDA_4_acc[:, 1]
validation_report4[:, 1] = LDA_4_std[:, 1]
validation_report4[:, 2] = LDA_CSP_4_acc[:, 1]
validation_report4[:, 3] = LDA_CSP_4_std[:, 1]
validation_report4[:, 4] = LDA_SACSP_4_acc[:, 1]
validation_report4[:, 5] = LDA_SACSP_4_std[:, 1]
print(validation_report4)
np.savetxt(validation_report4_path, validation_report4, fmt='%1.3f')

[[0.51  0.021 0.89  0.011 0.85  0.014]
 [0.47  0.02  0.82  0.019 0.66  0.018]
 [0.47  0.026 0.9   0.01  0.87  0.021]
 [0.52  0.044 0.74  0.015 0.61  0.019]
 [0.47  0.039 0.66  0.03  0.63  0.022]
 [0.53  0.015 0.76  0.018 0.66  0.021]
 [0.5   0.027 0.92  0.007 0.68  0.018]
 [0.52  0.016 0.92  0.008 0.84  0.012]
 [0.5   0.024 0.86  0.011 0.77  0.024]
 [0.52  0.042 0.95  0.012 0.93  0.03 ]
 [0.52  0.057 0.97  0.007 0.9   0.019]
 [0.54  0.053 0.96  0.013 0.83  0.028]
 [0.51  0.032 0.86  0.013 0.77  0.02 ]]


In [12]:
testing_report4[:, 0] = LDA_4_acc[:, 2]
testing_report4[:, 1] = LDA_4_std[:, 2]
testing_report4[:, 2] = LDA_CSP_4_acc[:, 2]
testing_report4[:, 3] = LDA_CSP_4_std[:, 2]
testing_report4[:, 4] = LDA_SACSP_4_acc[:, 2]
testing_report4[:, 5] = LDA_SACSP_4_std[:, 2]
print(testing_report4)
np.savetxt(testing_report4_path, testing_report4, fmt='%1.3f')

[[0.27  0.043 0.61  0.036 0.57  0.054]
 [0.26  0.048 0.56  0.043 0.26  0.029]
 [0.24  0.034 0.72  0.036 0.67  0.053]
 [0.24  0.053 0.36  0.068 0.27  0.035]
 [0.22  0.036 0.33  0.054 0.24  0.044]
 [0.25  0.051 0.36  0.057 0.34  0.069]
 [0.23  0.036 0.68  0.041 0.34  0.03 ]
 [0.27  0.031 0.71  0.045 0.64  0.047]
 [0.26  0.045 0.51  0.051 0.4   0.036]
 [0.27  0.07  0.82  0.033 0.8   0.095]
 [0.25  0.055 0.45  0.089 0.52  0.091]
 [0.23  0.043 0.52  0.066 0.31  0.089]
 [0.25  0.045 0.55  0.052 0.45  0.056]]
