In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt

In [2]:
## Path settings
results_dir = '/home/inffzy/Desktop/cogs189/cogs189_final_project/results'

## Classification results on data processed without ICA
LDA_______2_path = os.path.join(results_dir, '2_LDA.npy')
LDA_CSP___2_path = os.path.join(results_dir, '2_LDA_CSP.npy')
LDA_SACSP_2_path = os.path.join(results_dir, '2_LDA_SACSP.npy')
LDA_______4_path = os.path.join(results_dir, '4_LDA.npy')
LDA_CSP___4_path = os.path.join(results_dir, '4_LDA_CSP.npy')
LDA_SACSP_4_path = os.path.join(results_dir, '4_LDA_SACSP.npy')

## Classification results on data processed with ICA
LDA_______2_ica_path = os.path.join(results_dir, '2_LDA_ica.npy')
LDA_CSP___2_ica_path = os.path.join(results_dir, '2_LDA_CSP_ica.npy')
LDA_SACSP_2_ica_path = os.path.join(results_dir, '2_LDA_SACSP_ica.npy')
LDA_______4_ica_path = os.path.join(results_dir, '4_LDA_ica.npy')
LDA_CSP___4_ica_path = os.path.join(results_dir, '4_LDA_CSP_ica.npy')
LDA_SACSP_4_ica_path = os.path.join(results_dir, '4_LDA_SACSP_ica.npy')


training_report2_path = os.path.join(results_dir, 'training_report2.csv')
validation_report2_path = os.path.join(results_dir, 'validation_report2.csv')
testing_report2_path = os.path.join(results_dir, 'testing_report2.csv')

training_report4_path = os.path.join(results_dir, 'training_report4.csv')
validation_report4_path = os.path.join(results_dir, 'validation_report4.csv')
testing_report4_path = os.path.join(results_dir, 'testing_report4.csv')

In [3]:
## Load results
LDA_______2 = np.load(LDA_______2_path)
LDA_CSP___2 = np.load(LDA_CSP___2_path)
LDA_SACSP_2 = np.load(LDA_SACSP_2_path)
LDA_______4 = np.load(LDA_______4_path)
LDA_CSP___4 = np.load(LDA_CSP___4_path)
LDA_SACSP_4 = np.load(LDA_SACSP_4_path)

LDA_______2_ica = np.load(LDA_______2_ica_path)
LDA_CSP___2_ica = np.load(LDA_CSP___2_ica_path)
LDA_SACSP_2_ica = np.load(LDA_SACSP_2_ica_path)
LDA_______4_ica = np.load(LDA_______4_ica_path)
LDA_CSP___4_ica = np.load(LDA_CSP___4_ica_path)
LDA_SACSP_4_ica = np.load(LDA_SACSP_4_ica_path)

In [4]:
def get_acc_and_var(results, save_path=None):
    results_acc_over_experiment = np.mean(results, axis=0).round(2)
    results_std_over_experiment = np.std(results, axis=0).round(3)
    
    results_acc_over_subject = np.mean(results_acc_over_experiment, axis=0).round(2)
    results_std_over_subject = np.mean(results_std_over_experiment, axis=0).round(3)
    
    print(results_acc_over_experiment)
    print(results_acc_over_subject)
    print()
    print(results_std_over_experiment)
    print(results_std_over_subject)
    
    results_acc = np.concatenate((results_acc_over_experiment, np.atleast_2d(results_acc_over_subject)), axis=0)
    results_std = np.concatenate((results_std_over_experiment, np.atleast_2d(results_std_over_subject)), axis=0)
    
    return results_acc, results_std

In [5]:
## Calculate accuracy and standard deviation
LDA_______2_acc, LDA_______2_std = get_acc_and_var(LDA_______2)
LDA_CSP___2_acc, LDA_CSP___2_std = get_acc_and_var(LDA_CSP___2)
LDA_SACSP_2_acc, LDA_SACSP_2_std = get_acc_and_var(LDA_SACSP_2)
LDA_______4_acc, LDA_______4_std = get_acc_and_var(LDA_______4)
LDA_CSP___4_acc, LDA_CSP___4_std = get_acc_and_var(LDA_CSP___4)
LDA_SACSP_4_acc, LDA_SACSP_4_std = get_acc_and_var(LDA_SACSP_4)

LDA_______2_ica_acc, LDA_______2_ica_std = get_acc_and_var(LDA_______2_ica)
LDA_CSP___2_ica_acc, LDA_CSP___2_ica_std = get_acc_and_var(LDA_CSP___2_ica)
LDA_SACSP_2_ica_acc, LDA_SACSP_2_ica_std = get_acc_and_var(LDA_SACSP_2_ica)
LDA_______4_ica_acc, LDA_______4_ica_std = get_acc_and_var(LDA_______4_ica)
LDA_CSP___4_ica_acc, LDA_CSP___4_ica_std = get_acc_and_var(LDA_CSP___4_ica)
LDA_SACSP_4_ica_acc, LDA_SACSP_4_ica_std = get_acc_and_var(LDA_SACSP_4_ica)

[[0.89 0.52 0.58]
 [0.91 0.47 0.44]
 [0.91 0.54 0.45]
 [0.87 0.5  0.44]
 [0.83 0.44 0.42]
 [0.95 0.51 0.49]
 [0.8  0.46 0.46]
 [0.91 0.54 0.6 ]
 [0.95 0.48 0.49]
 [1.   0.45 0.48]
 [1.   0.64 0.58]
 [1.   0.54 0.48]]
[0.92 0.51 0.49]

[[0.039 0.052 0.054]
 [0.023 0.049 0.036]
 [0.04  0.041 0.06 ]
 [0.049 0.062 0.035]
 [0.024 0.08  0.07 ]
 [0.036 0.058 0.083]
 [0.041 0.047 0.057]
 [0.017 0.04  0.086]
 [0.025 0.044 0.08 ]
 [0.006 0.064 0.076]
 [0.    0.059 0.084]
 [0.    0.14  0.046]]
[0.025 0.061 0.064]
[[0.8  0.78 0.74]
 [0.71 0.67 0.52]
 [0.94 0.93 0.89]
 [0.79 0.78 0.62]
 [0.67 0.63 0.55]
 [0.79 0.77 0.51]
 [0.82 0.8  0.68]
 [0.96 0.96 0.91]
 [0.84 0.82 0.74]
 [0.95 0.94 0.9 ]
 [0.99 0.98 0.49]
 [0.98 0.98 0.84]]
[0.85 0.84 0.7 ]

[[0.019 0.02  0.047]
 [0.032 0.04  0.052]
 [0.016 0.015 0.032]
 [0.023 0.032 0.05 ]
 [0.04  0.032 0.066]
 [0.043 0.047 0.094]
 [0.033 0.035 0.063]
 [0.02  0.023 0.037]
 [0.026 0.032 0.07 ]
 [0.028 0.027 0.051]
 [0.015 0.021 0.115]
 [0.034 0.034 0.136]]
[0.0

In [6]:
## Initialize report matrices
training_report2 = np.empty((13, 6), dtype='U10')
validation_report2 = np.empty((13, 6), dtype='U10')
testing_report2 = np.empty((13, 6), dtype='U10')

training_report4 = np.empty((13, 6), dtype='U10')
validation_report4 = np.empty((13, 6), dtype='U10')
testing_report4 = np.empty((13, 6), dtype='U10')

In [7]:
## Fill and output report matrices

for i in range(13):
    training_report2[i, 0] = "{:.2f}".format(LDA_______2_acc[i, 0]) + '/' + "{:.3f}".format(LDA_______2_std[i, 0])
    training_report2[i, 1] = "{:.2f}".format(LDA_CSP___2_acc[i, 0]) + '/' + "{:.3f}".format(LDA_CSP___2_std[i, 0])
    training_report2[i, 2] = "{:.2f}".format(LDA_SACSP_2_acc[i, 0]) + '/' + "{:.3f}".format(LDA_SACSP_2_std[i, 0])
    training_report2[i, 3] = "{:.2f}".format(LDA_______2_ica_acc[i, 0]) + '/' + "{:.3f}".format(LDA_______2_ica_std[i, 0])
    training_report2[i, 4] = "{:.2f}".format(LDA_CSP___2_ica_acc[i, 0]) + '/' + "{:.3f}".format(LDA_CSP___2_ica_std[i, 0])
    training_report2[i, 5] = "{:.2f}".format(LDA_SACSP_2_ica_acc[i, 0]) + '/' + "{:.3f}".format(LDA_SACSP_2_ica_std[i, 0])
    
print(training_report2)
np.savetxt(training_report2_path, training_report2, fmt='%s')

[['0.89/0.039' '0.80/0.019' '0.77/0.052' '0.89/0.035' '0.81/0.034'
  '0.59/0.036']
 ['0.91/0.023' '0.71/0.032' '0.64/0.036' '0.89/0.021' '0.73/0.042'
  '0.61/0.042']
 ['0.91/0.040' '0.94/0.016' '0.89/0.037' '0.90/0.017' '0.94/0.017'
  '0.81/0.053']
 ['0.87/0.049' '0.79/0.023' '0.68/0.053' '0.90/0.036' '0.78/0.027'
  '0.59/0.036']
 ['0.83/0.024' '0.67/0.040' '0.66/0.035' '0.81/0.032' '0.67/0.046'
  '0.61/0.037']
 ['0.95/0.036' '0.79/0.043' '0.68/0.034' '0.97/0.011' '0.78/0.061'
  '0.60/0.052']
 ['0.80/0.041' '0.82/0.033' '0.60/0.052' '0.90/0.021' '0.84/0.020'
  '0.59/0.042']
 ['0.91/0.017' '0.96/0.020' '0.93/0.014' '0.92/0.023' '0.96/0.016'
  '0.91/0.043']
 ['0.95/0.025' '0.84/0.026' '0.75/0.044' '0.99/0.011' '0.82/0.032'
  '0.70/0.027']
 ['1.00/0.006' '0.95/0.028' '0.95/0.030' '1.00/0.000' '0.97/0.021'
  '0.71/0.084']
 ['1.00/0.000' '0.99/0.015' '0.91/0.035' '1.00/0.000' '0.99/0.013'
  '0.77/0.089']
 ['1.00/0.000' '0.98/0.034' '0.92/0.082' '1.00/0.000' '0.99/0.015'
  '0.79/0.154']
 ['0

In [8]:
for i in range(13):
    validation_report2[i, 0] = "{:.2f}".format(LDA_______2_acc[i, 1]) + '/' + "{:.3f}".format(LDA_______2_std[i, 1])
    validation_report2[i, 1] = "{:.2f}".format(LDA_CSP___2_acc[i, 1]) + '/' + "{:.3f}".format(LDA_CSP___2_std[i, 1])
    validation_report2[i, 2] = "{:.2f}".format(LDA_SACSP_2_acc[i, 1]) + '/' + "{:.3f}".format(LDA_SACSP_2_std[i, 1])
    validation_report2[i, 3] = "{:.2f}".format(LDA_______2_ica_acc[i, 1]) + '/' + "{:.3f}".format(LDA_______2_ica_std[i, 1])
    validation_report2[i, 4] = "{:.2f}".format(LDA_CSP___2_ica_acc[i, 1]) + '/' + "{:.3f}".format(LDA_CSP___2_ica_std[i, 1])
    validation_report2[i, 5] = "{:.2f}".format(LDA_SACSP_2_ica_acc[i, 1]) + '/' + "{:.3f}".format(LDA_SACSP_2_ica_std[i, 1])
    
print(validation_report2)
np.savetxt(validation_report2_path, validation_report2, fmt='%s')

[['0.52/0.052' '0.78/0.020' '0.75/0.064' '0.53/0.032' '0.79/0.032'
  '0.57/0.044']
 ['0.47/0.049' '0.67/0.040' '0.60/0.039' '0.49/0.031' '0.70/0.042'
  '0.60/0.036']
 ['0.54/0.041' '0.93/0.015' '0.87/0.054' '0.57/0.052' '0.93/0.021'
  '0.80/0.058']
 ['0.50/0.062' '0.78/0.032' '0.63/0.071' '0.52/0.036' '0.76/0.039'
  '0.55/0.033']
 ['0.44/0.080' '0.63/0.032' '0.64/0.035' '0.41/0.062' '0.64/0.047'
  '0.57/0.057']
 ['0.51/0.058' '0.77/0.047' '0.63/0.043' '0.53/0.047' '0.76/0.060'
  '0.54/0.050']
 ['0.46/0.047' '0.80/0.035' '0.57/0.064' '0.50/0.052' '0.82/0.028'
  '0.51/0.076']
 ['0.54/0.040' '0.96/0.023' '0.92/0.017' '0.56/0.047' '0.96/0.017'
  '0.90/0.047']
 ['0.48/0.044' '0.82/0.032' '0.74/0.040' '0.54/0.073' '0.82/0.027'
  '0.68/0.024']
 ['0.45/0.064' '0.94/0.027' '0.92/0.035' '0.48/0.065' '0.94/0.030'
  '0.68/0.078']
 ['0.64/0.059' '0.98/0.021' '0.87/0.032' '0.46/0.077' '0.98/0.016'
  '0.71/0.099']
 ['0.54/0.140' '0.98/0.034' '0.88/0.110' '0.55/0.098' '0.96/0.037'
  '0.71/0.192']
 ['0

In [9]:
for i in range(13):
    testing_report2[i, 0] = "{:.2f}".format(LDA_______2_acc[i, 2]) + '/' + "{:.3f}".format(LDA_______2_std[i, 2])
    testing_report2[i, 1] = "{:.2f}".format(LDA_CSP___2_acc[i, 2]) + '/' + "{:.3f}".format(LDA_CSP___2_std[i, 2])
    testing_report2[i, 2] = "{:.2f}".format(LDA_SACSP_2_acc[i, 2]) + '/' + "{:.3f}".format(LDA_SACSP_2_std[i, 2])
    testing_report2[i, 3] = "{:.2f}".format(LDA_______2_ica_acc[i, 2]) + '/' + "{:.3f}".format(LDA_______2_ica_std[i, 2])
    testing_report2[i, 4] = "{:.2f}".format(LDA_CSP___2_ica_acc[i, 2]) + '/' + "{:.3f}".format(LDA_CSP___2_ica_std[i, 2])
    testing_report2[i, 5] = "{:.2f}".format(LDA_SACSP_2_ica_acc[i, 2]) + '/' + "{:.3f}".format(LDA_SACSP_2_ica_std[i, 2])
    
print(testing_report2)
np.savetxt(testing_report2_path, testing_report2, fmt='%s')

[['0.58/0.054' '0.74/0.047' '0.67/0.055' '0.53/0.039' '0.75/0.063'
  '0.52/0.068']
 ['0.44/0.036' '0.52/0.052' '0.44/0.059' '0.46/0.053' '0.55/0.074'
  '0.44/0.081']
 ['0.45/0.060' '0.89/0.032' '0.85/0.077' '0.50/0.057' '0.91/0.028'
  '0.78/0.053']
 ['0.44/0.035' '0.62/0.050' '0.53/0.064' '0.47/0.063' '0.60/0.069'
  '0.50/0.055']
 ['0.42/0.070' '0.55/0.066' '0.50/0.066' '0.40/0.059' '0.52/0.063'
  '0.47/0.057']
 ['0.49/0.083' '0.51/0.094' '0.49/0.066' '0.50/0.055' '0.56/0.083'
  '0.43/0.040']
 ['0.46/0.057' '0.68/0.063' '0.49/0.080' '0.50/0.059' '0.70/0.033'
  '0.50/0.082']
 ['0.60/0.086' '0.91/0.037' '0.88/0.051' '0.61/0.092' '0.89/0.044'
  '0.88/0.073']
 ['0.49/0.080' '0.74/0.070' '0.68/0.033' '0.53/0.075' '0.75/0.066'
  '0.69/0.054']
 ['0.48/0.076' '0.90/0.051' '0.92/0.040' '0.46/0.103' '0.90/0.045'
  '0.64/0.124']
 ['0.58/0.084' '0.49/0.115' '0.66/0.119' '0.48/0.050' '0.52/0.089'
  '0.51/0.095']
 ['0.48/0.046' '0.84/0.136' '0.54/0.136' '0.44/0.083' '0.76/0.120'
  '0.62/0.237']
 ['0

In [10]:
for i in range(13):
    training_report4[i, 0] = "{:.2f}".format(LDA_______4_acc[i, 0]) + '/' + "{:.3f}".format(LDA_______4_std[i, 0])
    training_report4[i, 1] = "{:.2f}".format(LDA_CSP___4_acc[i, 0]) + '/' + "{:.3f}".format(LDA_CSP___4_std[i, 0])
    training_report4[i, 2] = "{:.2f}".format(LDA_SACSP_4_acc[i, 0]) + '/' + "{:.3f}".format(LDA_SACSP_4_std[i, 0])
    training_report4[i, 3] = "{:.2f}".format(LDA_______4_ica_acc[i, 0]) + '/' + "{:.3f}".format(LDA_______4_ica_std[i, 0])
    training_report4[i, 4] = "{:.2f}".format(LDA_CSP___4_ica_acc[i, 0]) + '/' + "{:.3f}".format(LDA_CSP___4_ica_std[i, 0])
    training_report4[i, 5] = "{:.2f}".format(LDA_SACSP_4_ica_acc[i, 0]) + '/' + "{:.3f}".format(LDA_SACSP_4_ica_std[i, 0])
    
print(training_report4)
np.savetxt(training_report4_path, training_report4, fmt='%s')

[['0.81/0.025' '0.75/0.029' '0.66/0.026' '0.77/0.020' '0.75/0.023'
  '0.46/0.059']
 ['0.80/0.026' '0.67/0.027' '0.49/0.026' '0.75/0.022' '0.69/0.029'
  '0.34/0.029']
 ['0.76/0.021' '0.79/0.022' '0.76/0.038' '0.80/0.031' '0.81/0.025'
  '0.53/0.022']
 ['0.67/0.029' '0.56/0.031' '0.42/0.020' '0.76/0.016' '0.56/0.037'
  '0.35/0.031']
 ['0.71/0.033' '0.46/0.022' '0.42/0.016' '0.69/0.033' '0.47/0.029'
  '0.35/0.021']
 ['0.91/0.024' '0.58/0.039' '0.49/0.040' '0.92/0.016' '0.58/0.037'
  '0.38/0.031']
 ['0.68/0.044' '0.82/0.019' '0.48/0.026' '0.78/0.026' '0.83/0.023'
  '0.34/0.039']
 ['0.79/0.025' '0.86/0.018' '0.73/0.022' '0.82/0.018' '0.86/0.023'
  '0.67/0.043']
 ['0.86/0.025' '0.75/0.019' '0.60/0.050' '0.98/0.009' '0.74/0.027'
  '0.54/0.029']
 ['0.99/0.008' '0.91/0.025' '0.88/0.068' '1.00/0.000' '0.90/0.015'
  '0.70/0.063']
 ['1.00/0.000' '0.96/0.018' '0.85/0.039' '1.00/0.000' '0.94/0.022'
  '0.70/0.031']
 ['1.00/0.000' '0.95/0.033' '0.76/0.063' '1.00/0.000' '0.97/0.019'
  '0.72/0.072']
 ['0

In [11]:
for i in range(13):
    validation_report4[i, 0] = "{:.2f}".format(LDA_______4_acc[i, 1]) + '/' + "{:.3f}".format(LDA_______4_std[i, 1])
    validation_report4[i, 1] = "{:.2f}".format(LDA_CSP___4_acc[i, 1]) + '/' + "{:.3f}".format(LDA_CSP___4_std[i, 1])
    validation_report4[i, 2] = "{:.2f}".format(LDA_SACSP_4_acc[i, 1]) + '/' + "{:.3f}".format(LDA_SACSP_4_std[i, 1])
    validation_report4[i, 3] = "{:.2f}".format(LDA_______4_ica_acc[i, 1]) + '/' + "{:.3f}".format(LDA_______4_ica_std[i, 1])
    validation_report4[i, 4] = "{:.2f}".format(LDA_CSP___4_ica_acc[i, 1]) + '/' + "{:.3f}".format(LDA_CSP___4_ica_std[i, 1])
    validation_report4[i, 5] = "{:.2f}".format(LDA_SACSP_4_ica_acc[i, 1]) + '/' + "{:.3f}".format(LDA_SACSP_4_ica_std[i, 1])
    
print(validation_report4)
np.savetxt(validation_report4_path, validation_report4, fmt='%s')

[['0.51/0.021' '0.89/0.011' '0.85/0.014' '0.53/0.027' '0.89/0.010'
  '0.66/0.036']
 ['0.47/0.020' '0.82/0.019' '0.66/0.018' '0.46/0.028' '0.84/0.010'
  '0.56/0.023']
 ['0.47/0.026' '0.90/0.010' '0.87/0.021' '0.52/0.024' '0.90/0.011'
  '0.74/0.020']
 ['0.52/0.044' '0.74/0.015' '0.61/0.019' '0.50/0.039' '0.74/0.016'
  '0.57/0.023']
 ['0.47/0.039' '0.66/0.030' '0.63/0.022' '0.47/0.039' '0.67/0.032'
  '0.58/0.023']
 ['0.53/0.015' '0.76/0.018' '0.66/0.021' '0.53/0.025' '0.76/0.018'
  '0.59/0.018']
 ['0.50/0.027' '0.92/0.007' '0.68/0.018' '0.52/0.029' '0.92/0.008'
  '0.54/0.035']
 ['0.52/0.016' '0.92/0.008' '0.84/0.012' '0.52/0.023' '0.92/0.010'
  '0.81/0.024']
 ['0.50/0.024' '0.86/0.011' '0.77/0.024' '0.51/0.034' '0.86/0.011'
  '0.73/0.015']
 ['0.52/0.042' '0.95/0.012' '0.93/0.030' '0.51/0.035' '0.95/0.010'
  '0.82/0.050']
 ['0.52/0.057' '0.97/0.007' '0.90/0.019' '0.53/0.057' '0.97/0.010'
  '0.81/0.025']
 ['0.54/0.053' '0.96/0.013' '0.83/0.028' '0.52/0.064' '0.97/0.016'
  '0.84/0.041']
 ['0

In [12]:
for i in range(13):
    testing_report4[i, 0] = "{:.2f}".format(LDA_______4_acc[i, 2]) + '/' + "{:.3f}".format(LDA_______4_std[i, 2])
    testing_report4[i, 1] = "{:.2f}".format(LDA_CSP___4_acc[i, 2]) + '/' + "{:.3f}".format(LDA_CSP___4_std[i, 2])
    testing_report4[i, 2] = "{:.2f}".format(LDA_SACSP_4_acc[i, 2]) + '/' + "{:.3f}".format(LDA_SACSP_4_std[i, 2])
    testing_report4[i, 3] = "{:.2f}".format(LDA_______4_ica_acc[i, 2]) + '/' + "{:.3f}".format(LDA_______4_ica_std[i, 2])
    testing_report4[i, 4] = "{:.2f}".format(LDA_CSP___4_ica_acc[i, 2]) + '/' + "{:.3f}".format(LDA_CSP___4_ica_std[i, 2])
    testing_report4[i, 5] = "{:.2f}".format(LDA_SACSP_4_ica_acc[i, 2]) + '/' + "{:.3f}".format(LDA_SACSP_4_ica_std[i, 2])
    
print(testing_report4)
np.savetxt(testing_report4_path, testing_report4, fmt='%s')

[['0.27/0.043' '0.61/0.036' '0.57/0.054' '0.29/0.039' '0.62/0.036'
  '0.34/0.063']
 ['0.26/0.048' '0.56/0.043' '0.26/0.029' '0.25/0.041' '0.57/0.048'
  '0.20/0.033']
 ['0.24/0.034' '0.72/0.036' '0.67/0.053' '0.26/0.047' '0.72/0.043'
  '0.46/0.058']
 ['0.24/0.053' '0.36/0.068' '0.27/0.035' '0.23/0.053' '0.37/0.063'
  '0.23/0.029']
 ['0.22/0.036' '0.33/0.054' '0.24/0.044' '0.22/0.038' '0.32/0.065'
  '0.22/0.033']
 ['0.25/0.051' '0.36/0.057' '0.34/0.069' '0.29/0.047' '0.35/0.059'
  '0.26/0.037']
 ['0.23/0.036' '0.68/0.041' '0.34/0.030' '0.28/0.037' '0.71/0.044'
  '0.23/0.018']
 ['0.27/0.031' '0.71/0.045' '0.64/0.047' '0.27/0.042' '0.71/0.036'
  '0.62/0.050']
 ['0.26/0.045' '0.51/0.051' '0.40/0.036' '0.25/0.036' '0.51/0.044'
  '0.45/0.049']
 ['0.27/0.070' '0.82/0.033' '0.80/0.095' '0.28/0.053' '0.82/0.041'
  '0.59/0.084']
 ['0.25/0.055' '0.45/0.089' '0.52/0.091' '0.20/0.077' '0.44/0.089'
  '0.40/0.087']
 ['0.23/0.043' '0.52/0.066' '0.31/0.089' '0.20/0.058' '0.52/0.096'
  '0.55/0.113']
 ['0